# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\x0cgrpc.testing\"/\n\nServerInfo\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\r\n\x05media\x18\x02 \x01(\t\"~\n\x0bServerState\x12.\n\x05state\x18\x01 \x01(\x0e\x32\x1f.grpc.testing.ServerState.State\"?\n\x05State\x12\r\n\tUNDEFINED\x10\x00\x12\r\n\tCONNECTED\x10\x01\x12\r\n\tSTREAMING\x10\x06\x12\t\n\x05\x45NDED\x10\x07\"4\n\x10StreamingRequest\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"\x8b\x01\n\x11StreamingResponse\x12-\n\tcall_info\x18\x01 \x01(\x0b\x32\x18.grpc.testing.ServerInfoH\x00\x12/\n\ncall_state\x18\x02 \x01(\x0b\x32\x19.grpc.testing.ServerStateH\x00\x42\x16\n\x14stream_call_response2`\n\x0cStreamServer\x12P\n\tStreaming\x12\x1e.grpc.testing.StreamingRequest\x1a\x1f.grpc.testing.StreamingResponse(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVERINFO._serialized_start=33
  _SERVERINFO._serialized_end=80
  _SERVERSTATE._serialized_start=82
  _SERVERSTATE._serialized_end=208
  _SERVERSTATE_STATE._serialized_start=145
  _SERVERSTATE_STATE._serialized_end=208
  _STREAMINGREQUEST._serialized_start=210
  _STREAMINGREQUEST._serialized_end=262
  _STREAMINGRESPONSE._serialized_start=265
  _STREAMINGRESPONSE._serialized_end=404
  _STREAMSERVER._serialized_start=406
  _STREAMSERVER._serialized_end=502
# @@protoc_insertion_point(module_scope)
